version: "3.9"
services:
  wog:
    build:
      context: .
      dockerfile: Dockerfile
    image: ofirdassa/wog:wog
    ports:
      - "5000:5000"
  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    image: ofirdassa/wog:wog_tests
    environment:
      - HOSTIP=host.docker.internal
    depends_on:
      - wog